name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    # runs-on: self-hosted 
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Prepare ActiveBasic
        uses: ./.github/actions/install_activebasic
          
      - name: build app
        run: |
          .\screenshot.ps1 test1.png 
          .\.build\ActiveBasic\BasicCompiler.exe helloworld_rgbalib.abp ./helloworld_rgbalib.exe 
          .\screenshot.ps1 test2.png 
          tree /F
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name:  activebasic-on-github-actions-bin
          path: |
            .\helloworld_rgbalib.exe
            *.png
